server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: user-service-get-by-id
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/{id}
            - Method=GET
          filters:
            - SetPath=/api/user/{id}
        - id: user-service-user-all
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/all
            - Method=GET
          filters:
            - SetPath=/api/user/all
        - id: user-service-create-user
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - SetPath=/api/user
        - id: user-service-add-favorite-movie
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/{id}/favoriteMovie
            - Method=POST
          filters:
            - SetPath=/api/user/{id}/favoriteMovie
        - id: user-service-add-favorite-serie
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/{id}/favoriteSerie
            - Method=POST
          filters:
            - SetPath=/api/user/{id}/favoriteSerie
        - id: user-service-delete-favorite-movie
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/{id}/favoriteMovie/{mediaCode}
            - Method=DELETE
          filters:
            - SetPath=/api/user/{id}/favoriteMovie/{mediaCode}
        - id: user-service-delete-favorite-serie
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/{id}/favoriteSerie/{mediaCode}
            - Method=DELETE
          filters:
            - SetPath=/api/user/{id}/favoriteSerie/{mediaCode}

        - id: media-service-movies-by-media-codes
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/movies
          filters:
            - SetPath=/api/media/movie
        - id: media-service-movie-mediacode
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/movies/{mediaCode}
            - Method=GET
          filters:
            - SetPath=/api/media/movie/{mediaCode}
        - id: media-service-movie-all
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/movies/all
            - Method=GET
          filters:
            - SetPath=/api/media/movie/all
        - id: media-service-movie-update
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/movies/{id}
            - Method=PUT
          filters:
            - SetPath=/api/media/movie/{id}
        - id: media-service-movie-create
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/movies
            - Method=POST
          filters:
            - SetPath=/api/media/movie

        - id: media-service-series-by-media-codes
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/series
          filters:
            - SetPath=/api/media/serie
        - id: media-service-serie-mediacode
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/series/{mediaCode}
            - Method=GET
          filters:
            - SetPath=/api/media/serie/{mediaCode}
        - id: media-service-serie-all
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/series/all
            - Method=GET
          filters:
            - SetPath=/api/media/serie/all
        - id: media-service-serie-update
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/series/{id}
            - Method=PUT
          filters:
            - SetPath=/api/media/serie/{id}
        - id: media-service-serie-create
          uri: http://${MEDIA_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/series
            - Method=POST
          filters:
            - SetPath=/api/media/serie