apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-subscription-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-media-pvc
spec:
  accessModes:
    - ReadWriteOnce   
  resources:
    requests:
      storage: 1Gi
