Vagrant.configure("2") do |config|
  config.vm.define "movieplex"
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "private_network", ip: "192.168.56.5"
  config.vm.provider "virtualbox" do |v|
    v.name = "movieplex"
    v.memory = 4096
    v.cpus = 4
  end
  
  config.vm.hostname = "movieplex"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "./script.sh"
end